services:
  routing:
    container_name: "ready_addon_routing"
    build:
      context: ./routing
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8787:80"
    volumes:
      - ./routing/nginx/log:/var/log/nginx/
    depends_on:
      - backend_nginx
      - backend_php
      - backend_redis
      - backend_postgresql
    networks:
      - ready_addon
    restart: unless-stopped

  backend_nginx:
    container_name: "ready_addon_backend_nginx"
    build:
      context: ./backend/dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9012:80"
    volumes:
      - ./backend/src:/var/www/html:delegated
      - ./backend/nginx/log:/var/log/nginx/
    depends_on:
      - backend_php
      - backend_redis
      - backend_postgresql
    networks:
      - ready_addon
    restart: unless-stopped

  backend_php:
    container_name: "ready_addon_backend_php"
    build:
      context: ./backend/dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9099:9000"
    volumes:
      - ./backend/src:/var/www/html:delegated
      - ./backend/dockerfiles/configs/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - ready_addon
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: dev

  backend_postgresql:
    image: postgres:16.2
    container_name: "ready_addon_backend_postgresql"
    environment:
      POSTGRES_DB: ${BACKEND_DB_DATABASE}
      POSTGRES_USER: ${BACKEND_DB_USERNAME}
      POSTGRES_PASSWORD: ${BACKEND_DB_PASSWORD}
      TZ: Europe/Sarajevo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${BACKEND_DB_DATABASE} -U ${BACKEND_DB_USERNAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend/postgresql/data:/var/lib/postgresql/data
      - ./backend/postgresql/logs:/var/log/postgresql
    ports:
      - "5499:5432"
    networks:
      - ready_addon
    restart: unless-stopped
    shm_size: 128mb

  backend_redis:
    container_name: "ready_addon_backend_redis"
    image: redis:alpine
    ports:
      - "6479:6379"
    volumes:
      - ./backend/redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    networks:
      - ready_addon
    restart: unless-stopped

  backend_composer:
    container_name: "ready_addon_backend_composer"
    build:
      context: ./backend/dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./backend/src:/var/www/html
    depends_on:
      - backend_php
    entrypoint: ["composer", "--ignore-platform-reqs"]
    networks:
      - ready_addon

  backend_artisan:
    container_name: "ready_addon_backend_artisan"
    build:
      context: ./backend/dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./backend/src:/var/www/html:delegated
    depends_on:
      - backend_postgresql
      - backend_redis
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - ready_addon

  frontend_node:
    stdin_open: true
    container_name: "ready_addon_frontend_vue"
    build:
      context: ./frontend/dockerfiles
      dockerfile: node.dockerfile
    volumes:
      - ./frontend/src:/var/www/html:delegated
    networks:
      - ready-addon

  frontend_nginx:
    container_name: "ready_addon_frontend_nginx"
    build:
      context: ./frontend/dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "3000:80"
    volumes:
      - ./frontend/src:/var/www/html:delegated
      - ./frontend/nginx/log:/var/log/nginx/
    depends_on:
      - backend_php
      - backend_redis
      - backend_postgresql
    networks:
      - ready_addon
    restart: unless-stopped

networks:
  ready_addon:
    driver: bridge