services:
  frontend_app:
    stdin_open: true
    container_name: "ready_addon_frontend_app"
    build:
      context: ../
      dockerfile: ./dockerfiles/node.dockerfile
    volumes:
      - ../app:/var/www/html:delegated
    networks:
      - ready_addon
    entrypoint: ["/usr/local/bin/npm"]
    #command: npm install & npm build

  frontend_app_npx:
    stdin_open: true
    container_name: "ready_addon_frontend_app_npx"
    build:
      context: ../
      dockerfile: ./dockerfiles/node.dockerfile
    volumes:
      - ../app:/var/www/html:delegated
    networks:
      - ready_addon
    entrypoint: ["/usr/local/bin/npx"]

  frontend_nginx:
    container_name: "ready_addon_frontend_nginx"
    build:
      context: ../
      dockerfile: ./dockerfiles/nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "3022:8080"
    volumes:
      - ../app:/var/www/html:delegated
      - ../mount/nginx/log:/var/log/nginx/
    depends_on:
      - backend_php
      - backend_redis
      - backend_postgresql
    networks:
      - ready_addon
    restart: unless-stopped