services:
  frontend_node:
    stdin_open: true
    container_name: "ready_addon_frontend_vue"
    build:
      dockerfile: node.dockerfile
    volumes:
      - ../app:/var/www/html:delegated
    networks:
      - ready_addon

  frontend_nginx:
    container_name: "ready_addon_frontend_nginx"
    build:
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "3000:80"
    volumes:
      - ../app:/var/www/html:delegated
      - ../mount/nginx/log:/var/log/nginx/
    depends_on:
      - backend_php
      - backend_redis
      - backend_postgresql
    networks:
      - ready_addon
    restart: unless-stopped